/// <reference path="../typings/tsd.d.ts" />
var MyKoopError = require("./MyKoopError");
var DatabaseError = require("./DatabaseError");
var ApplicationError = require("./ApplicationError");
MyKoopError.DatabaseError = DatabaseError;
MyKoopError.ApplicationError = ApplicationError;
var ValidationError = require("./ValidationError");
var ResourceNotFoundError = require("./ResourceNotFoundError");
var AccessDeniedError = require("./AccessDeniedError");
ApplicationError.ResourceNotFoundError = ResourceNotFoundError;
ApplicationError.AccessDeniedError = AccessDeniedError;
ApplicationError.ValidationError = ValidationError;
module.exports = MyKoopError;
